org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.251
loader_version_range=[1,)

mod_id=ss_advanced_crafting
mod_name=SS Advanced Crafting
mod_license=MIT
mod_version=1.0.0
mod_group_id=dev.renzo.ssadvancedcrafting
mod_authors=Renzo
mod_description=Adds an Advanced Crafting Upgrade for Sophisticated Storage with an in-GUI recipe book that pulls ingredients from storage inventory and player inventory.
